### ISSUE TITLE
railway上部署后报错了

### ISSUE THREAD

**Issue by EtonArcher** [CaoYunzhou/cocopilot-gpt#1]
![image](https://github.com/CaoYunzhou/cocopilot-gpt/assets/130029758/44f6d13c-a878-4a3f-b234-8d10d125f07b)
你好 我按照说明部署到railway上，部署的时候提示需要wsgi，请求后提示proxy没返回，我应该怎么处理？

**Comment by CaoYunzhou** [comment]
这个我没看懂噢，请求体和日志看看？
