### ISSUE TITLE
调用出现错误

### ISSUE THREAD

**Issue by leichinkang** [CaoYunzhou/cocopilot-gpt#13]
反代后，调用域名/v1/chat/completions出现如下错误：

Failed to fetch

Access to fetch at 'https:/xxxxxx/v1/chat/completions' from origin 'https://xxxxxxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
main.js?attr=HvgONv0cy9nUC1rffVhoNhopH-pA_kAEnZaMGDcVZqkitM:4004 
        
        
       POST https://xxxxxx/v1/chat/completions net::ERR_FAILED
fetchCallImpl @ main.js?attr=HvgONv0cy9nUC1rffVhoNhC1lFyWBH-pA_kAEnZaMGDcVZqkitM:4004
fetch @ main.js?attr=HvgONv0cy9nUC1rffVhA_kAEnZaMGDcVZqkitM:4010
wM @ index-5634dda1.js:283
handleSubmit @ index-5634dda1.js:295
b @ index-5634dda1.js:299
uK @ index-5634dda1.js:5
hK @ index-5634dda1.js:5
fK @ index-5634dda1.js:5
RB @ index-5634dda1.js:5
HB @ index-5634dda1.js:5
(anonymous) @ index-5634dda1.js:5
Y9 @ index-5634dda1.js:8
Gv @ index-5634dda1.js:5
$5 @ index-5634dda1.js:5
O5 @ index-5634dda1.js:5
NK @ index-5634dda1.js:5
index-5634dda1.js:299 Failed to fetch
userscript.html?name=%25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4-%25E6%2594%25B9.user.js&id=0f8cfb4c-2615-412b-b56e-f50857e88bd1:844 关闭了快捷键
userscript.html?name=%25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4-%25E6%2594%25B9.user.js&id=0f8cfb4c-2615-412b-b56e-f50857e88bd1:841 Uncaught TypeError: Cannot read properties of undefined (reading 'shortcut')
    at HTMLDocument.hotkey (userscript.html?name=%25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4-%25E6%2594%25B9.user.js&id=0f8cfb4c-2615-412b-b56e-f50857e88bd1:841:63)

**Comment by leichinkang** [comment]
这个错误表明你的网页尝试从一个不同的域https://XXXXXX) 获取资源,而浏览器因为同源策略 (Same-Origin Policy)而阻止了这个请求
具体而言，错误信息中指出了问题是CORS (跨源资源共享) 政策导致的。服务器未在响应中包含必要的 CORS 头部信息，尤其是缺少了Access-Control-Allow-Origin’ 头部。这意味着浏览器拒绝从一个源 (
https://XXXXX ) 向另一个源( https://XXXXX ) 发起跨域请求。
要解决这个问题，有几种可能的方法
服务器端配置:在服务端
https://XXXXXX ) 配置响应头，添加允许来自你网页的跨域请求的头部信o仕反方饰日阿应中添人
Access-Control-Allow-Origin: https://ai.deviner.link
这将允许来自 https://XXXXXX的请求访问该资源。
代理请求: 如果你无法更改服务器端的配置，可以考虑通过你的服务器代理请求。你的服务器可以转发请求到
https://XXXXXX 并返回结果给你的网页。这种方式绕过了浏览器的同源策略。
使用 JSONP 或 WebSocket: 如果服务器支持JSONP 或 WebSocket，这也是绕过同源策略的方法。请注意，这两种方法也需要服务器的支持。
选择哪种方法取决于你对服务端的控制权以及服务端的支持能力。

**Comment by CaoYunzhou** [comment]
跨域的问题
