### ISSUE TITLE
post失败，状态500

### ISSUE THREAD

**Issue by cjw-666** [CaoYunzhou/cocopilot-gpt#2]
服务现在还可用吗？
![截屏2023-11-21 17 24 08](https://github.com/CaoYunzhou/cocopilot-gpt/assets/39663688/d7c26ce8-f8ae-408c-8637-2414ae2348a4)

**Comment by CaoYunzhou** [comment]
一直都可以用的呀

**Comment by CaoYunzhou** [comment]
![截图_选择区域_20231121205702](https://github.com/CaoYunzhou/cocopilot-gpt/assets/28099773/5f772977-5a30-4fd5-a45d-65014906095b)
测试了没问题的

**Comment by cjw-666** [comment]
谢谢老板答疑
