### ISSUE TITLE
模型错误

### ISSUE THREAD

**Issue by q1034806313** [CaoYunzhou/cocopilot-gpt#6]
除了gpt-4这个模型以外
其他4.0模型全部都是假的
请问是copilot的原因吗？
还是说本程序把其他模型重定向到3.5了呢？
包括32k，连鲁迅问题都回答不了
只有问他是什么模型能答对
调用速度也是，除了gpt-4这一个模型慢
其他都是飞快的，不知道为什么我部署后也是没有流式输出，nginx缓存已经off了

**Comment by CaoYunzhou** [comment]
copilot只支持gpt-4模型

**Comment by CaoYunzhou** [comment]
其他模型都是3.5

**Comment by q1034806313** [comment]
> 其他模型都是3.5

其他模型能不能全部定向到gpt-4呢大佬
