### ISSUE TITLE
流式输出

### ISSUE THREAD

**Issue by q212199936** [CaoYunzhou/cocopilot-gpt#8]
经过两个方式部署贵项目测试如下:
1.使用服务器直接docker部署并用ip调用,因nextweb直接调用报错所以加在oneapi渠道里,然后使用nextweb调用oneapi的接口,经测试此方法无流式回复。
2.使用宝塔安装docker并用nginx反代到端口8080,且关闭nginx缓存,再同样加入到oneapi里,调用也无流式回复。

请大佬核实

**Comment by q212199936** [comment]
经过使用您的cocopilot.aivvm.com这个网站作为调用接口,使用后除了gpt-4没有流式其余都是有的,gpt-4这个模型到最后也会快速的输出完,前面需要等待很久

**Comment by CaoYunzhou** [comment]
![image](https://github.com/CaoYunzhou/cocopilot-gpt/assets/28099773/c51cc827-30e1-40e4-bc77-96ce7e76a979)

流式输出是没问题的

**Comment by q212199936** [comment]
> ![image](https://private-user-images.githubusercontent.com/28099773/290079429-c51cc827-30e1-40e4-bc77-96ce7e76a979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTE4NjQsIm5iZiI6MTcwMjQ1MTU2NCwicGF0aCI6Ii8yODA5OTc3My8yOTAwNzk0MjktYzUxY2M4MjctMzBlMS00MGU0LWJjNzctOTZjZTdlNzZhOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3MTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNzdlYjU0NjIxMTkwMTk3ZDkxZWQxZDg2MDRlNDE4M2I5ZmE0ZDQ0ODYxZDFhMWY4ZGRkZTJiNTQxYmEyNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkAE_zM-uyOZuMXF1J-W8YfQ4PhJ4S6_R_n7qUEC3IE)
> 
> 流式输出是没问题的

我测试放oneapi渠道里是没有的 , 请问有交流群或者联系方式吗 , 请教一下

**Comment by CaoYunzhou** [comment]
https://t.me/aijingshenyuan
